name: Update Filtered Domains

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每两天运行一次 (UTC 0:00)
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write  # 授予写权限以允许 commit 和 push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 使用 Python 3.12

      - name: Run script
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add filtered_ad_domains.txt
          git commit -m 'Auto-update filtered ad domains' || echo "No changes to commit"
          git push
